import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { adminApi, type AdminCohort, type AdminContent, type AuditLog, type ExportJob, type Overview, type Version } from '../admin-api';
import type { Feedback } from '../types';

type Section = 'dashboard' | 'contents' | 'cohorts' | 'exports' | 'system';
const sections: [Section, string][] = [['dashboard', '대시보드'], ['contents', '콘텐츠'], ['cohorts', '코호트'], ['exports', '내보내기'], ['system', '감사·시스템']];
const date = (value?: string | null) => value ? new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';

function Login({ onLogin }: { onLogin: () => void }) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget);
    try { await adminApi.login(String(data.get('id')), String(data.get('password'))); onLogin(); }
    catch (reason) { setError((reason as Error).message); } finally { setBusy(false); }
  }
  return <main className="admin-login"><section><p className="eyebrow">NXT CLOUD · CONTROL ROOM</p><h1>관리자 로그인</h1><p>콘텐츠와 코호트, 내보내기 작업을 관리합니다.</p><form onSubmit={submit}><label htmlFor="adminId">관리자 아이디</label><input id="adminId" name="id" autoComplete="username" required /><label htmlFor="adminPassword">비밀번호</label><input id="adminPassword" name="password" type="password" autoComplete="current-password" required />{error && <p role="alert" className="admin-error">{error}</p>}<button disabled={busy}>{busy ? '확인 중…' : '로그인'}</button></form><a href="/">← 공개 갤러리</a></section></main>;
}

function Dashboard({ overview, cohorts, audits }: { overview: Overview | null; cohorts: AdminCohort[]; audits: AuditLog[] }) {
  const summary = overview?.summary; return <><header className="admin-heading"><div><p className="eyebrow">OPERATIONS OVERVIEW</p><h1>운영 현황</h1></div><p>원본 파일을 바꾸지 않고 메타데이터와 작업 상태를 관리합니다.</p></header><div className="admin-metrics"><article><span>전체 콘텐츠</span><strong id="overviewTotal">{summary?.totalContents ?? '—'}개</strong></article><article><span>웹페이지 / 게임</span><strong>{summary ? `${summary.webpageCount} / ${summary.gameCount}` : '—'}</strong></article><article><span>누적 버전</span><strong>{summary?.totalVersions ?? '—'}</strong></article><article><span>운영 코호트</span><strong>{cohorts.filter((item) => item.status === 'active').length}</strong></article></div><div className="admin-panels"><article><p className="eyebrow">STORAGE</p><h2>저장 경로 전환 상태</h2><dl><div><dt>v2 contents</dt><dd>{overview?.storage.v2Contents ?? '—'}</dd></div><div><dt>legacy games</dt><dd>{overview?.storage.legacyGames ?? '—'}</dd></div><div><dt>확인 필요</dt><dd>{overview?.storage.unknown ?? '—'}</dd></div></dl></article><article><p className="eyebrow">RECENT ACTIVITY</p><h2>최근 관리자 작업</h2>{audits.length ? <ul className="plain-list">{audits.slice(0, 5).map((item) => <li key={item.auditId}><b>{item.action}</b><span>{item.actorId} · {date(item.occurredAt)}</span></li>)}</ul> : <p className="admin-muted">기록된 작업이 없습니다.</p>}</article></div></>;
}

function ContentDetail({ content, cohorts, onClose, onChanged }: { content: AdminContent; cohorts: AdminCohort[]; onClose: () => void; onChanged: () => void }) {
  const [versions, setVersions] = useState<Version[]>([]); const [feedback, setFeedback] = useState<Feedback[]>([]); const [notice, setNotice] = useState(''); const [confirmId, setConfirmId] = useState('');
  useEffect(() => { Promise.all([adminApi.versions(content.contentId), adminApi.feedback(content.contentId)]).then(([v, f]) => { setVersions(v.versions); setFeedback(f.feedback); }).catch((e) => setNotice(e.message)); }, [content.contentId]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await adminApi.updateContent(content.contentId, { title: data.get('title'), cohortId: data.get('cohortId'), owner: { kind: data.get('ownerKind'), name: data.get('ownerName') }, contentType: data.get('contentType') }); setNotice('콘텐츠 정보를 저장했습니다.'); onChanged(); } catch (e) { setNotice((e as Error).message); } }
  async function resetPassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await adminApi.resetContentPassword(content.contentId, String(data.get('newPassword'))); event.currentTarget.reset(); setNotice('업데이트 비밀번호를 변경했습니다.'); } catch (e) { setNotice((e as Error).message); } }
  async function removeFeedback(createdAt: string) { try { await adminApi.deleteFeedback(content.contentId, createdAt); setFeedback((items) => items.filter((item) => item.createdAt !== createdAt)); setNotice('피드백을 삭제했습니다.'); } catch (e) { setNotice((e as Error).message); } }
  async function removeContent() { if (confirmId !== content.contentId) return; try { await adminApi.deleteContent(content.contentId); onChanged(); onClose(); } catch (e) { setNotice((e as Error).message); } }
  return <aside className="admin-drawer" aria-label="콘텐츠 상세"><div className="drawer-head"><div><p className="eyebrow">CONTENT DETAIL</p><h2>{content.title}</h2><code>{content.contentId}</code></div><button className="quiet" onClick={onClose}>닫기</button></div>{notice && <p role="status" className="admin-notice">{notice}</p>}<form className="admin-form" onSubmit={save}><label>제목<input name="title" defaultValue={content.title} maxLength={60} required /></label><div className="form-grid"><label>코호트<select name="cohortId" defaultValue={content.cohort?.cohortId}>{cohorts.map((item) => <option value={item.cohortId} key={item.cohortId}>{item.name}</option>)}</select></label><label>유형<select name="contentType" defaultValue={content.contentType}><option value="webpage">웹페이지</option><option value="game">게임</option></select></label><label>소유 구분<select name="ownerKind" defaultValue={content.owner.kind}><option value="individual">개인</option><option value="team">팀</option></select></label><label>이름 / 팀명<input name="ownerName" defaultValue={content.owner.name} required /></label></div><button>정보 저장</button></form><section className="drawer-section"><h3>버전 {versions.length}개</h3><ul className="plain-list">{versions.map((item) => <li key={item.version}><b>v{item.version} · {item.originalFileName || 'HTML'}</b><span>{item.sizeBytes.toLocaleString()} bytes · {date(item.uploadedAt)}</span><code>{item.objectKey}</code></li>)}</ul></section><section className="drawer-section"><h3>피드백 {feedback.length}개</h3>{feedback.map((item) => <article className="feedback-row" key={item.createdAt}><p>{item.message}</p><small>{item.nickname} · {date(item.createdAt)}</small><button className="danger-quiet" onClick={() => removeFeedback(item.createdAt)}>이 피드백 삭제</button></article>)}</section><section className="drawer-section danger-zone"><h3>민감 작업</h3><form className="inline-form" onSubmit={resetPassword}><input name="newPassword" type="password" minLength={4} maxLength={30} placeholder="새 업데이트 비밀번호" required /><button>비밀번호 변경</button></form><p>콘텐츠 삭제 확인을 위해 ID를 그대로 입력하세요.</p><div className="inline-form"><input value={confirmId} onChange={(event) => setConfirmId(event.target.value)} placeholder={content.contentId} /><button className="danger" disabled={confirmId !== content.contentId} onClick={removeContent}>콘텐츠 영구 삭제</button></div></section></aside>;
}

function Contents({ items, total, cohorts, busy, pageIndex, nextCursor, onFilter, onPrevious, onNext, onRefresh }: { items: AdminContent[]; total: number; cohorts: AdminCohort[]; busy: boolean; pageIndex: number; nextCursor: string | null; onFilter: (query: string) => void; onPrevious: () => void; onNext: () => void; onRefresh: () => void }) {
  const [selected, setSelected] = useState<AdminContent | null>(null);
  function filter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const d = new FormData(event.currentTarget); const p = new URLSearchParams(); for (const key of ['query', 'cohortId', 'type']) { const value = String(d.get(key) || ''); if (value) p.set(key, value); } onFilter(p.toString()); }
  return <><header className="admin-heading"><div><p className="eyebrow">CONTENT REGISTRY</p><h1>콘텐츠</h1></div><strong>{total}개의 콘텐츠</strong></header><form className="admin-filter" onSubmit={filter}><input name="query" aria-label="콘텐츠 검색" placeholder="제목, 이름, 수업 검색" /><select name="cohortId" aria-label="코호트 필터"><option value="">전체 코호트</option>{cohorts.map((item) => <option value={item.cohortId} key={item.cohortId}>{item.name}</option>)}</select><select name="type" aria-label="콘텐츠 유형 필터"><option value="">전체 유형</option><option value="webpage">웹페이지</option><option value="game">게임</option></select><button>검색</button></form>{busy ? <p role="status">불러오는 중…</p> : <div className="admin-table-wrap"><table><thead><tr><th>콘텐츠</th><th>코호트</th><th>유형</th><th>버전</th><th>저장</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.contentId}><td><b>{item.title}</b><small>{item.owner.name} · {item.contentId}</small></td><td>{item.cohort?.name || '—'}</td><td>{item.contentType === 'game' ? '게임' : '웹페이지'}</td><td>v{item.latestVersion}</td><td><code>{item.storageScheme}</code></td><td><button className="quiet" onClick={() => setSelected(item)}>검토</button></td></tr>)}</tbody></table></div>}<nav className="admin-pager" aria-label="관리자 콘텐츠 페이지"><button className="quiet" disabled={pageIndex === 0 || busy} onClick={onPrevious}>← 이전 25개</button><span>{pageIndex + 1} 페이지</span><button className="quiet" disabled={!nextCursor || busy} onClick={onNext}>다음 25개 →</button></nav>{selected && <ContentDetail content={selected} cohorts={cohorts} onClose={() => setSelected(null)} onChanged={onRefresh} />}</>;
}

function Cohorts({ cohorts, onChanged }: { cohorts: AdminCohort[]; onChanged: () => void }) {
  const [notice, setNotice] = useState(''); async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const d = new FormData(form); try { await adminApi.createCohort({ name: d.get('name'), dateLabel: d.get('dateLabel') }); form.reset(); setNotice('코호트를 만들었습니다.'); onChanged(); } catch (e) { setNotice((e as Error).message); } }
  async function toggle(item: AdminCohort) { try { await adminApi.updateCohort(item.cohortId, { status: item.status === 'active' ? 'archived' : 'active' }); onChanged(); } catch (e) { setNotice((e as Error).message); } }
  return <><header className="admin-heading"><div><p className="eyebrow">COHORTS</p><h1>코호트</h1></div><strong>{cohorts.length}개</strong></header>{notice && <p role="status" className="admin-notice">{notice}</p>}<form className="admin-filter" onSubmit={create}><input name="name" aria-label="새 코호트 이름" placeholder="새 코호트 이름" maxLength={60} required /><input name="dateLabel" aria-label="코호트 일정" placeholder="일정 (선택)" maxLength={20} /><button>코호트 추가</button></form><div className="cohort-admin-list">{cohorts.map((item) => <article key={item.cohortId}><div><small>{item.cohortId}</small><h2>{item.name}</h2><p>{item.dateLabel || '일정 미정'} · {item.submissionMode === 'team' ? '팀 제출' : '개인 제출'}</p></div><span className={`state ${item.status}`}>{item.status}</span>{item.editable ? <button className="quiet" onClick={() => toggle(item)}>{item.status === 'active' ? '보관' : '활성화'}</button> : <small>기본 코호트</small>}</article>)}</div></>;
}

function Exports({ cohorts, jobs, onChanged }: { cohorts: AdminCohort[]; jobs: ExportJob[]; onChanged: () => void }) {
  const [notice, setNotice] = useState(''); async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const id = String(new FormData(event.currentTarget).get('cohortId')); try { await adminApi.createExport(id); setNotice('ZIP 작업을 요청했습니다. 상태가 완료되면 다운로드할 수 있습니다.'); onChanged(); } catch (e) { setNotice((e as Error).message); } }
  async function retry(id: string) { try { await adminApi.retryExport(id); onChanged(); } catch (e) { setNotice((e as Error).message); } }
  return <><header className="admin-heading"><div><p className="eyebrow">ASYNC EXPORT</p><h1>코호트 ZIP 다운로드</h1></div><p>파일명에 코호트·이름/팀명·제목·버전을 반영하고 manifest를 포함합니다.</p></header><form className="export-create" onSubmit={create}><label>다운로드할 코호트<select name="cohortId" required><option value="">선택하세요</option>{cohorts.map((item) => <option key={item.cohortId} value={item.cohortId}>{item.name}</option>)}</select></label><button>ZIP 생성 요청</button></form>{notice && <p role="status" className="admin-notice">{notice}</p>}<div className="export-list">{jobs.length ? jobs.map((job) => <article key={job.exportId}><div><b>{job.cohort}</b><small>{date(job.requestedAt)} · 시도 {job.attempt}</small></div><span className={`state ${job.status}`}>{job.status}</span>{job.downloadUrl ? <a className="admin-button" href={job.downloadUrl}>다운로드</a> : job.status === 'failed' ? <button className="quiet" onClick={() => retry(job.exportId)}>재시도</button> : null}</article>) : <p className="admin-muted">최근 내보내기 작업이 없습니다.</p>}</div></>;
}

function System({ audits }: { audits: AuditLog[] }) {
  const [notice, setNotice] = useState(''); async function submit(event: FormEvent<HTMLFormElement>, kind: 'password' | 'admin') { event.preventDefault(); const form = event.currentTarget; const d = new FormData(form); try { if (kind === 'password') await adminApi.changePassword(String(d.get('currentPassword')), String(d.get('newPassword'))); else await adminApi.addAdmin(String(d.get('id')), String(d.get('password'))); form.reset(); setNotice(kind === 'password' ? '관리자 비밀번호를 변경했습니다.' : '관리자 계정을 추가했습니다.'); } catch (e) { setNotice((e as Error).message); } }
  return <><header className="admin-heading"><div><p className="eyebrow">AUDIT & SYSTEM</p><h1>감사·시스템</h1></div><p>관리자 변경 이력과 접근 계정을 관리합니다.</p></header>{notice && <p role="status" className="admin-notice">{notice}</p>}<div className="admin-panels"><article><h2>내 비밀번호 변경</h2><form className="admin-form" onSubmit={(e) => submit(e, 'password')}><label>현재 비밀번호<input name="currentPassword" type="password" required /></label><label>새 비밀번호<input name="newPassword" type="password" minLength={8} required /></label><button>비밀번호 변경</button></form></article><article><h2>관리자 추가</h2><form className="admin-form" onSubmit={(e) => submit(e, 'admin')}><label>아이디<input name="id" required /></label><label>초기 비밀번호<input name="password" type="password" minLength={8} required /></label><button>관리자 추가</button></form></article></div><div className="audit-list"><h2>최근 감사 로그</h2>{audits.map((item) => <article key={item.auditId}><time>{date(item.occurredAt)}</time><b>{item.action}</b><span>{item.actorId}</span><code>{item.targetType}{item.targetId ? ` · ${item.targetId}` : ''}</code></article>)}</div></>;
}

export function AdminPage() {
  const [auth, setAuth] = useState<'checking' | 'out' | 'in'>('checking'); const [section, setSection] = useState<Section>('dashboard'); const [contents, setContents] = useState<AdminContent[]>([]); const [total, setTotal] = useState(0); const [nextCursor, setNextCursor] = useState<string | null>(null); const [cursorHistory, setCursorHistory] = useState<(string | null)[]>([null]); const [pageIndex, setPageIndex] = useState(0); const [cohorts, setCohorts] = useState<AdminCohort[]>([]); const [overview, setOverview] = useState<Overview | null>(null); const [audits, setAudits] = useState<AuditLog[]>([]); const [jobs, setJobs] = useState<ExportJob[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [filter, setFilter] = useState('');
  const load = useCallback(async (nextFilter = '', cursor: string | null = null) => { setBusy(true); setError(''); const cursorParam = cursor ? `${nextFilter ? `${nextFilter}&` : ''}cursor=${encodeURIComponent(cursor)}` : nextFilter; try { const [c, h, o, a, e] = await Promise.all([adminApi.contents(cursorParam), adminApi.cohorts(), adminApi.overview(), adminApi.audits(), adminApi.exports()]); setContents(c.contents); setTotal(c.page.total); setNextCursor(c.page.nextCursor); setCohorts(h.cohorts); setOverview(o.overview); setAudits(a.auditLogs); setJobs(e.exports); } catch (reason) { const e = reason as Error & { status?: number }; if (e.status === 401) setAuth('out'); else setError(e.message); } finally { setBusy(false); } }, []);
  useEffect(() => { adminApi.session().then(() => { setAuth('in'); return load(''); }).catch(() => setAuth('out')); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { document.title = '관리자 · NXT Cloud Showcase'; }, []);
  const activeCount = useMemo(() => cohorts.filter((item) => item.status === 'active').length, [cohorts]);
  if (auth === 'checking') return <main className="admin-loading" role="status">관리자 세션을 확인하는 중입니다.</main>;
  if (auth === 'out') return <Login onLogin={() => { setAuth('in'); load(''); }} />;
  const refresh = () => load(filter, cursorHistory[pageIndex]); const setFilters = (value: string) => { setFilter(value); setCursorHistory([null]); setPageIndex(0); load(value, null); }; const previousPage = () => { if (!pageIndex) return; const index = pageIndex - 1; setPageIndex(index); load(filter, cursorHistory[index]); }; const nextPage = () => { if (!nextCursor) return; const history = [...cursorHistory.slice(0, pageIndex + 1), nextCursor]; setCursorHistory(history); setPageIndex(pageIndex + 1); load(filter, nextCursor); };
  return <div className="admin-app"><header className="admin-topbar"><a href="/" className="admin-brand">NXT CLOUD <b>ADMIN</b></a><div><span>{total} contents · {activeCount} active cohorts</span><button className="quiet" onClick={refresh}>새로고침</button><button className="quiet" onClick={() => adminApi.logout().finally(() => setAuth('out'))}>로그아웃</button></div></header><div className="admin-layout"><nav aria-label="관리자 메뉴">{sections.map(([id, label], index) => <button key={id} aria-current={section === id ? 'page' : undefined} onClick={() => setSection(id)}><span>{String(index + 1).padStart(2, '0')}</span>{label}</button>)}</nav><main className="admin-main">{error && <p role="alert" className="admin-error">{error} <button className="quiet" onClick={refresh}>다시 시도</button></p>}{section === 'dashboard' && <Dashboard overview={overview} cohorts={cohorts} audits={audits} />}{section === 'contents' && <Contents items={contents} total={total} cohorts={cohorts} busy={busy} pageIndex={pageIndex} nextCursor={nextCursor} onFilter={setFilters} onPrevious={previousPage} onNext={nextPage} onRefresh={refresh} />}{section === 'cohorts' && <Cohorts cohorts={cohorts} onChanged={refresh} />}{section === 'exports' && <Exports cohorts={cohorts} jobs={jobs} onChanged={refresh} />}{section === 'system' && <System audits={audits} />}</main></div></div>;
}
